version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3316:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=nexpoint
    volumes:
      - mysql-data:/var/lib/mysql
      - ./BackEnd/database:/docker-entrypoint-initdb.d
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_NAME=nexpoint
      - DATABASE_URL=mysql://root:my-secret-pw@mysql:3306/nexpoint
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: