# Dockerfile-frontend

# Usar uma imagem oficial do Node.js para o build
FROM node:22.13.0 AS builder

# Diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Copiar o package.json e instalar as dependências
COPY FrontEnd/package*.json ./
RUN npm install

# Copiar o código do frontend
COPY FrontEnd/ .

# Construir a aplicação Next.js (gerando a pasta .next)
RUN npm run build

# Etapa 2: Configuração para rodar em produção
FROM node:22.13.0

# Diretório de trabalho no container
WORKDIR /usr/src/app

# Copiar somente os arquivos necessários da etapa de build
COPY --from=builder /usr/src/app /usr/src/app

# Expor a porta em que o Next.js vai rodar (3000 por padrão)
EXPOSE 3000

# Definir a variável de ambiente para rodar em produção
ENV NODE_ENV=production

# Rodar o Next.js em produção
CMD ["npm", "run", "start"]
