# Dockerfile-backend

# Usar uma imagem oficial do Node.js
FROM node:22.13.0

# Diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Copiar as dependências do package.json
COPY BackEnd/package*.json ./

# Instalar as dependências
RUN npm install

# Copiar todo o código do backend para o container
COPY BackEnd/ .

# Expor a porta onde o backend vai rodar
EXPOSE 4000

# Definir variáveis de ambiente no Dockerfile
ENV DATABASE_URL ="mysql://root:my-secret-pw@mysql:3306/nexpoint"

# Comando para rodar o backend
CMD ["npm", "run", "dev"]
